name: Deploy EC2

on:
  workflow_call:

jobs:

  EC2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
    # Artifact name
        name: programa

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: /home/${{ secrets.REMOTE_USER }}
        EXCLUDE: "/postgres-data/"

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          export HOST=${{ secrets.DB_HOST }} 
          export USER=${{ secrets.DB_USER }}
          export PASSWORD=${{ secrets.DB_PASSWORD }} 
          export DBNAME=${{ secrets.DB_NAME }}
          export PORT=${{ secrets.DB_PORT }}
